#index:
#    path: /
#    controller: App\Controller\DefaultController::index
#
save_image_route:
    path: /save_image_file
    controller: App\Controller\ImageController::main
    options:
        expose: true